---
title: "Untitled"
author: "Lucas Melfi"
date: "2026-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("esquisse")
install.packages("plotly")
library (esquisse)
library(plotly)
library(tidyverse)
library(readxl)
library(janitor)
library(scales)
library(forcats)
library(readxl)
options(scipen = 999)

```


```{r}

exp_prod <- read_excel("Datasets/Malvinas/Nongeo/falkland-islandss-exported-products-1.xlsx")
exp_prod <- exp_prod %>% clean_names()
exp_prod <- exp_prod %>%
  mutate(across(c(starts_with("exports"), starts_with("share")), as.numeric))
str(exp_prod)



```

```{r}
top5_exprod <- exp_prod %>%
  slice_max(exports_usd, n = 5) %>%
  arrange(desc(exports_usd))
```

```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), y = exports_usd) +
  geom_col(fill = "#112446") +
  scale_y_continuous(labels = label_number(scale = 1e-6, suffix = " M")) +
  theme_minimal()

```
```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), y = exports_usd) +
  geom_col(fill = "#112446") +
  scale_y_continuous(labels = label_number(scale = 1e-6, suffix = " M")) + 
  labs(
    title = "Top 5 exportaciones",
    x = "Producto (HS4)",
    y = "Exportaciones (millones USD)"
  ) +  
  theme_minimal()

```
```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), y = exports_usd) +
  geom_col(fill = "#112446") +
  scale_y_continuous(labels = label_number(scale = 1e-6, suffix = " M")) + 
  labs(
    title = "Top 5 exportaciones",
    x = "Producto (HS4)",
    y = "Exportaciones (millones USD)")+
    geom_text(aes(label = round(exports_usd/1e6, 1)), 
            vjust = -0.3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), y = exports_usd) +
  geom_col(fill = "#112446") +
  scale_y_continuous(labels = label_number(scale = 1e-6, suffix = " M")) + 
  labs(
    title = "Top 5 exportaciones",
    x = "Producto (HS4)",
    y = "Exportaciones (millones USD)")+ 
  geom_text(aes(label = label_number(scale = 1e-6, suffix = " M")(exports_usd)), 
            vjust = -0.3) +
  scale_y_continuous(labels = label_number(scale = 1e-6, suffix = " M")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), 
      y = exports_usd) +
  geom_col(fill = "#112446") +
  geom_text(
    aes(label = scales::label_number(scale = 1e-6, suffix = " M")(exports_usd)),
    vjust = 1.5,
    color = "white"
  ) +
  scale_y_continuous(labels = scales::label_number(scale = 1e-6, suffix = " M")) +
  labs(
    title = "Top 5 exportaciones",
    x = "Producto (HS4)",
    y = "Exportaciones (millones USD)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(top5_exprod) +
  aes(x = fct_reorder(hs4, exports_usd, .desc = TRUE), 
      y = exports_usd) +
  geom_col(fill = "#112446") +
  geom_text(
    aes(
      label = scales::label_number(scale = 1e-6, suffix = " M")(exports_usd),
      vjust = ifelse(exports_usd > max(exports_usd)*0.6, 1.5, -0.3),
      color = ifelse(exports_usd > max(exports_usd)*0.6, "white", "black")
    )
  ) +
  scale_y_continuous(labels = scales::label_number(scale = 1e-6, suffix = " M")) +
  labs(
    title = "Top 5 exportaciones Islas Malvinas 2023",
    x = "Producto (HS4)",
    y = "Exportaciones (millones USD)"
  ) +
  theme_minimal() +
  theme(
  axis.text.x = element_text(angle = 45, hjust = 1),
  legend.position = "none",
  plot.title = element_text(
    size = 16,
    face = "bold",
    hjust = 0.5, 
    color = "grey40"
  )
)
```



```{r}
ggplot(top5_exprod) +
  aes(
    x = fct_reorder(hs4, share_percent, .desc = TRUE),
    y = share_percent
  ) +

  geom_col(fill = "#112446") +

  geom_text(
    aes(
      label = paste0(round(share_percent, 1), "%"),
      vjust = ifelse(share_percent > 10, 1.5, -0.5),
      color = ifelse(share_percent > 10, "white", "#8B0000")
    )
  ) +

  scale_color_identity() +

  scale_y_continuous(
    labels = \(x) paste0(x, "%")
  ) +

  labs(
    title = "Top 5 exportaciones",
    x = "Producto (HS4)",
    y = "Participación de mercado (%)"
  ) +

  theme_minimal() +

  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```



```{r}
imp_prod <- read_excel("Datasets/Malvinas/Nongeo/falkland-islandss-imported-products-1.xlsx")
View(imp_prod)
```





```{r}
impo_orig <- read_excel("Datasets/Malvinas/Nongeo/falkland-islandss-import-origins-1.xlsx")
View(impo_orig)

```

```{r}
imp_orig <- imp_orig %>% clean_names()
imp_orig <- imp_orig %>%
  mutate(
    imports_usd = as.numeric(imports_usd)
  )

imp_orig <- imp_orig %>%
  mutate(
    share_2024 = imports_usd / sum(imports_usd)
  )
top5_cimp <- imp_orig %>%
  slice_max(imports_usd, n = 5) %>%
  arrange(desc(imports_usd))



```
``




```{r}
ggplot(top5_cimp) +
  aes(
    x = fct_reorder(country, share_2024, .desc = TRUE),
    y = share_2024
  ) +
  geom_col(fill = "#112446") +

  geom_text(
    aes(label = scales::percent(share_2024, accuracy = 0.01)),
    vjust = -0.5
  ) +

  scale_y_continuous(
    labels = scales::label_percent()
  ) +
  labs(
    title = "Importaciones por país",
    x = "País",
    y = "(%) importaciones"
  ) +

  theme_minimal()
```
```{r}
exp_des <- read_excel("Datasets/Malvinas/Nongeo/falkland-islandss-export-destinations-1.xlsx")
View(exp_des)
exp_des <- exp_des %>% clean_names()
exp_des <- exp_des %>%
  mutate(
    exports_usd = as.numeric(exports_usd)
  )
exp_des <- exp_des %>%
  mutate(
    share_2024 = exports_usd / sum(exports_usd)
  )

top5_cexp <- exp_des %>%
  slice_max(exports_usd, n = 5) %>%
  arrange(desc(exports_usd))





str(top5_cexp)

```

```{r}
ggplot(top5_cexp) +
  aes(
    x = fct_reorder(country, share_2024, .desc = TRUE),
    y = share_2024
  ) +
  geom_col(fill = "#112446") +

  geom_text(
    aes(label = scales::percent(share_2024, accuracy = 0.01)),
    vjust = -0.5
  ) +

  scale_y_continuous(
    labels = scales::label_percent()
  ) +
  labs(
    title = "Exportaciones por país",
    x = "País",
    y = "(%) importaciones"
  ) +

  theme_minimal()
```


```{r}
gasto_uk <- gasto_uk %>% 
  select(-c(1, 2, 3))

gasto_uk2 <- gasto_uk %>% 
  pivot_longer(
    cols = where(is.numeric),
    names_to = "anio",
    values_to = "pbi_pct"
  )
write.csv(gasto_uk2, "gasto_uk.csv", row.names = FALSE )

```

```{r}
g_imports <- read_excel("Datasets/Malvinas/Nongeo/falkland-islandss-imported-products-1.xlsx")
View(g_imports)
str
```

```{r}
str(imp_orig)
```

